spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/user_service
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:qPgrIvrucqeSw9uxEAJi+eXaec2nhkfPLbJvig1NDJw=}
  access-token-expiration: 1800000
  refresh-token-expiration: 7200000
  token-hash-secret: ${TOKEN_HASH_SECRET:R9wb7kn+0NBiAqH+WeAVCvZco2dZB9RK4nECj6n1Mp4=}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
