package com.flab.user.config.exception

import org.springframework.http.HttpStatus

enum class MessageCode(
    val code: String,
    val message: String,
    val status: HttpStatus
) {

    UNKNOWN_EXCEPTION("UNKNOWN_EXCEPTION", "알 수 없는 오류가 발생했습니다", HttpStatus.INTERNAL_SERVER_ERROR)
    , METHOD_ARGUMENT_NOT_VALID_EXCEPTION("METHOD_ARGUMENT_NOT_VALID_EXCEPTION", "잘못된 데이터입력", HttpStatus.BAD_REQUEST)
    , DUPLICATED_EMAIL("DUPLICATED_EMAIL","이미 사용중인 이메일입니다.", HttpStatus.BAD_REQUEST)
    , REGISTER_SUCCESS("REGISTER_SUCCESS", "가입성공", HttpStatus.CREATED)

    , REGISTER_FAIL("REGISTER_FAIL", "가입실패", HttpStatus.INTERNAL_SERVER_ERROR)
    , USER_ALREADY_EXISTS_EXCEPTION("USER_ALREADY_EXISTS_EXCEPTION", "가입되어있음", HttpStatus.CONFLICT)
    , DATA_ALREADY_EXISTS_EXCEPTION("DATA_ALREADY_EXISTS_EXCEPTION", "데이터가있음", HttpStatus.CONFLICT)
    , DATA_NOT_FOUND_EXCEPTION("DATA_NOT_FOUND_EXCEPTION", "데이터가 없음", HttpStatus.NOT_FOUND)
    , USER_NOT_FOUND("USER_NOT_FOUND_EXCEPTION", "사용자가 없음", HttpStatus.NOT_FOUND)
    , DATA_INTEGRITY_VIOLATION_EXCEPTION("DATA_INTEGRITY_VIOLATION_EXCEPTION", "데이터 오류", HttpStatus.BAD_REQUEST)
    , BAD_CREDENTIAL_EXCEPTION("BAD_CREDENTIAL_EXCEPTION", "잘못된 회원정보", HttpStatus.UNAUTHORIZED)
    , INVALIDATE_CLAIMS_EXCEPTION("INVALIDATE_CLAIMS_EXCEPTION", "인증 오류", HttpStatus.UNAUTHORIZED)
    , INVALID_VERIFICATION_CODE("INVALID_VERIFICATION_CODE", "인증 코드 오류", HttpStatus.BAD_REQUEST)
    , EXCEEDED_MAX_ATTEMPTS("EXCEEDED_MAX_ATTEMPTS", "최대 입력 횟수 초과", HttpStatus.BAD_REQUEST)
    , INSUFFICIENT_COIN("INSUFFICIENT_COIN", "코인 부족", HttpStatus.BAD_REQUEST)
    , SEND_MESSAGE_FAIL("SEND_MESSAGE_FAIL", "메시지 전송 실패", HttpStatus.INTERNAL_SERVER_ERROR)
    , INSUFFICIENT_AUTHENTICATION("INSUFFICIENT_AUTHENTICATION_EXCEPTION", "인증 만료", HttpStatus.UNAUTHORIZED)
    , INVALIDATE_REFRESH_TOKEN("INVALIDATE_REFRESH_TOKEN_EXCEPTION", "유효하지 않는 리프레시 토큰", HttpStatus.UNAUTHORIZED);
}